//! Generated Integration Tests (Contract Checks)
//! 
//! This file is auto-generated by cdd-rust. 
//! It verifies that the implementation follows the OpenAPI contract.

use reqwest::Client;
use serde_json::json;
const OPENAPI_PATH: &str = "../petstore.json";

#[tokio::test]
async fn test_sdk_add_pet() {
    let client = reqwest::Client::new();
    let base_url = "http://localhost:8080/v2";
    let auth_token = Some("special-key");
    let body: cdd_rust_client_2::models::Pet = Default::default();
    let result = cdd_rust_client_2::handlers::pet::add_pet(&client, base_url, auth_token, body).await;
    // Test should pass if the request successfully leaves the client and parses the mock response
    assert!(result.is_ok(), "expected ok response, got {:?}", result.err());
}

#[tokio::test]
async fn test_sdk_update_pet() {
    let client = reqwest::Client::new();
    let base_url = "http://localhost:8080/v2";
    let auth_token = Some("special-key");
    let body: cdd_rust_client_2::models::Pet = Default::default();
    let result = cdd_rust_client_2::handlers::pet::update_pet(&client, base_url, auth_token, body).await;
    // Test should pass if the request successfully leaves the client and parses the mock response
    assert!(result.is_ok(), "expected ok response, got {:?}", result.err());
}

#[tokio::test]
async fn test_sdk_find_pets_by_status() {
    let client = reqwest::Client::new();
    let base_url = "http://localhost:8080/v2";
    let query: cdd_rust_client_2::handlers::pet::FindPetsByStatusQuery = serde_json::from_value(serde_json::json!({ "status": ["available"] })).unwrap();
    let auth_token = Some("special-key");
    let result = cdd_rust_client_2::handlers::pet::find_pets_by_status(&client, base_url, query, auth_token).await;
    assert!(result.is_ok(), "expected 200 OK and valid JSON parsing, got {:?}", result.err());
}

#[tokio::test]
async fn test_sdk_find_pets_by_tags() {
    let client = reqwest::Client::new();
    let base_url = "http://localhost:8080/v2";
    let query: cdd_rust_client_2::handlers::pet::FindPetsByTagsQuery = Default::default();
    let auth_token = Some("special-key");
    let result = cdd_rust_client_2::handlers::pet::find_pets_by_tags(&client, base_url, query, auth_token).await;
    // Test should pass if the request successfully leaves the client and parses the mock response
    assert!(result.is_ok(), "expected ok response, got {:?}", result.err());
}

#[tokio::test]
async fn test_sdk_get_pet_by_id() {
    let client = reqwest::Client::new();
    let base_url = "http://localhost:8080/v2";
    let pet_id: i64 = 1;
    let auth_token = Some("special-key");
    let result = cdd_rust_client_2::handlers::pet::get_pet_by_id(&client, base_url, pet_id, auth_token).await;
    // Test should pass if the request successfully leaves the client and parses the mock response
    assert!(result.is_ok(), "expected ok response, got {:?}", result.err());
}

#[tokio::test]
async fn test_sdk_update_pet_with_form() {
    let client = reqwest::Client::new();
    let base_url = "http://localhost:8080/v2";
    let pet_id: i64 = 1;
    let auth_token = Some("special-key");
    let result = cdd_rust_client_2::handlers::pet::update_pet_with_form(&client, base_url, pet_id, auth_token).await;
    // Test should pass if the request successfully leaves the client and parses the mock response
    assert!(result.is_ok(), "expected ok response, got {:?}", result.err());
}

#[tokio::test]
async fn test_sdk_delete_pet() {
    let client = reqwest::Client::new();
    let base_url = "http://localhost:8080/v2";
    let pet_id: i64 = 1;
    let api_key = "special-key".to_string();
    let auth_token = Some("special-key");
    let result = cdd_rust_client_2::handlers::pet::delete_pet(&client, base_url, pet_id, api_key, auth_token).await;
    // Test should pass if the request successfully leaves the client and parses the mock response
    assert!(result.is_ok(), "expected ok response, got {:?}", result.err());
}

#[tokio::test]
async fn test_sdk_upload_file() {
    let client = reqwest::Client::new();
    let base_url = "http://localhost:8080/v2";
    let pet_id: i64 = 1;
    let auth_token = Some("special-key");
    let result = cdd_rust_client_2::handlers::pet::upload_file(&client, base_url, pet_id, auth_token).await;
    // Test should pass if the request successfully leaves the client and parses the mock response
    assert!(result.is_ok(), "expected ok response, got {:?}", result.err());
}

#[tokio::test]
async fn test_sdk_get_inventory() {
    let client = reqwest::Client::new();
    let base_url = "http://localhost:8080/v2";
    let auth_token = Some("special-key");
    let result = cdd_rust_client_2::handlers::store::get_inventory(&client, base_url, auth_token).await;
    assert!(result.is_ok(), "expected 200 OK and valid JSON parsing, got {:?}", result.err());
}

#[tokio::test]
async fn test_sdk_place_order() {
    let client = reqwest::Client::new();
    let base_url = "http://localhost:8080/v2";
    let body: cdd_rust_client_2::models::Order = Default::default();
    let result = cdd_rust_client_2::handlers::store::place_order(&client, base_url, body).await;
    // Test should pass if the request successfully leaves the client and parses the mock response
    assert!(result.is_ok(), "expected ok response, got {:?}", result.err());
}

#[tokio::test]
async fn test_sdk_get_order_by_id() {
    let client = reqwest::Client::new();
    let base_url = "http://localhost:8080/v2";
    let order_id: i64 = 1;
    let result = cdd_rust_client_2::handlers::store::get_order_by_id(&client, base_url, order_id).await;
    // Test should pass if the request successfully leaves the client and parses the mock response
    assert!(result.is_ok(), "expected ok response, got {:?}", result.err());
}

#[tokio::test]
async fn test_sdk_delete_order() {
    let client = reqwest::Client::new();
    let base_url = "http://localhost:8080/v2";
    let order_id: i64 = 1;
    let result = cdd_rust_client_2::handlers::store::delete_order(&client, base_url, order_id).await;
    // Test should pass if the request successfully leaves the client and parses the mock response
    assert!(result.is_ok(), "expected ok response, got {:?}", result.err());
}

#[tokio::test]
async fn test_sdk_create_user() {
    let client = reqwest::Client::new();
    let base_url = "http://localhost:8080/v2";
    let body: cdd_rust_client_2::models::User = Default::default();
    let result = cdd_rust_client_2::handlers::user::create_user(&client, base_url, body).await;
    // Test should pass if the request successfully leaves the client and parses the mock response
    assert!(result.is_ok(), "expected ok response, got {:?}", result.err());
}

#[tokio::test]
async fn test_sdk_create_users_with_array_input() {
    let client = reqwest::Client::new();
    let base_url = "http://localhost:8080/v2";
    let body: Vec<cdd_rust_client_2::models::User> = Default::default();
    let result = cdd_rust_client_2::handlers::user::create_users_with_array_input(&client, base_url, body).await;
    // Test should pass if the request successfully leaves the client and parses the mock response
    assert!(result.is_ok(), "expected ok response, got {:?}", result.err());
}

#[tokio::test]
async fn test_sdk_create_users_with_list_input() {
    let client = reqwest::Client::new();
    let base_url = "http://localhost:8080/v2";
    let body: Vec<cdd_rust_client_2::models::User> = Default::default();
    let result = cdd_rust_client_2::handlers::user::create_users_with_list_input(&client, base_url, body).await;
    // Test should pass if the request successfully leaves the client and parses the mock response
    assert!(result.is_ok(), "expected ok response, got {:?}", result.err());
}

#[tokio::test]
async fn test_sdk_login_user() {
    let client = reqwest::Client::new();
    let base_url = "http://localhost:8080/v2";
    let query: cdd_rust_client_2::handlers::user::LoginUserQuery = serde_json::from_value(serde_json::json!({ "username": "user1", "password": "test_pass" })).unwrap();
    let result = cdd_rust_client_2::handlers::user::login_user(&client, base_url, query).await;
    // Test should pass if the request successfully leaves the client and parses the mock response
    assert!(result.is_ok(), "expected ok response, got {:?}", result.err());
}

#[tokio::test]
async fn test_sdk_logout_user() {
    let client = reqwest::Client::new();
    let base_url = "http://localhost:8080/v2";
    let result = cdd_rust_client_2::handlers::user::logout_user(&client, base_url).await;
    // Test should pass if the request successfully leaves the client and parses the mock response
    assert!(result.is_ok(), "expected ok response, got {:?}", result.err());
}

#[tokio::test]
async fn test_sdk_get_user_by_name() {
    let client = reqwest::Client::new();
    let base_url = "http://localhost:8080/v2";
    let username: String = "test_value".to_string();
    let result = cdd_rust_client_2::handlers::user::get_user_by_name(&client, base_url, username).await;
    // Test should pass if the request successfully leaves the client and parses the mock response
    assert!(result.is_ok(), "expected ok response, got {:?}", result.err());
}

#[tokio::test]
async fn test_sdk_update_user() {
    let client = reqwest::Client::new();
    let base_url = "http://localhost:8080/v2";
    let username: String = "test_value".to_string();
    let body: cdd_rust_client_2::models::User = Default::default();
    let result = cdd_rust_client_2::handlers::user::update_user(&client, base_url, username, body).await;
    // Test should pass if the request successfully leaves the client and parses the mock response
    assert!(result.is_ok(), "expected ok response, got {:?}", result.err());
}

#[tokio::test]
async fn test_sdk_delete_user() {
    let client = reqwest::Client::new();
    let base_url = "http://localhost:8080/v2";
    let username: String = "test_value".to_string();
    let result = cdd_rust_client_2::handlers::user::delete_user(&client, base_url, username).await;
    // Test should pass if the request successfully leaves the client and parses the mock response
    assert!(result.is_ok(), "expected ok response, got {:?}", result.err());
}

