#!/bin/bash

# Generates a feature support dashboard by checking which OpenAPI features
# are supported across different toolchains based on their COMPLIANCE.md files.
# It then updates the root COMPLIANCE.md file with a dashboard matrix.

set -e

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_FILE="$ROOT_DIR/ECOSYSTEM_COMPLIANCE_OAS_3_2_0.md"

cd "$ROOT_DIR"

TOOLCHAINS="cdd-c cdd-cpp cdd-csharp cdd-go cdd-java cdd-kotlin cdd-php cdd-python-all cdd-ruby cdd-rust cdd-sh cdd-swift cdd-ts"

# Define the features to track based on standard OpenAPI concepts
FEATURES=(
    "Info Object"
    "Server Object"
    "Components Object"
    "Paths Object"
    "Path Item Object"
    "Operation Object"
    "Parameter Object"
    "Request Body Object"
    "Responses Object"
    "Responses / Schema Object"
    "Reference Object"
    "OAuth Flows"
    "Security Requirement Object"
    "Links / Callbacks"
    "Webhooks"
)

# Start writing the new COMPLIANCE.md
cat << 'EOF' > "$OUTPUT_FILE"
# CDD OpenAPI Feature Support Dashboard

This dashboard automatically tracks the implementation status of key OpenAPI 3.2.0 features across the various CDD toolchains.

It is generated by parsing the `COMPLIANCE.md` files within each language-specific submodule.

## Support Matrix

| Feature | cdd-c | cdd-cpp | cdd-csharp | cdd-go | cdd-java | cdd-kotlin | cdd-php | cdd-python-all | cdd-ruby | cdd-rust | cdd-sh | cdd-swift | cdd-ts |
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
EOF

# Process each feature
for feature in "${FEATURES[@]}"; do
    row="| $feature |"
    
    for toolchain in $TOOLCHAINS; do
        compliance_file="$toolchain/COMPLIANCE.md"
        status="❌" # Default to not supported
        
        # Check if the compliance file exists for the toolchain
        if [ -f "$toolchain/COMPLIANCE.md" ]; then
            # We look for the feature name (case-insensitive) and see if it's marked with a checkmark or mentioned under a "Supported" list.
            
            # Map features to potential keywords found in COMPLIANCE files
            search_pattern="$feature"
            case "$feature" in
                "Info Object") search_pattern="Info Object" ;;
                "Server Object") search_pattern="Server Object" ;;
                "Components Object") search_pattern="Components Object\|Components.*Schemas" ;;
                "Paths Object") search_pattern="Paths Object\|Paths\|Operations & Paths" ;;
                "Path Item Object") search_pattern="Path Item" ;;
                "Operation Object") search_pattern="Operation Object\|Operations" ;;
                "Parameter Object") search_pattern="Parameter Object" ;;
                "Request Body Object") search_pattern="Request Body" ;;
                "Responses Object") search_pattern="Responses Object" ;;
                "Responses / Schema Object") search_pattern="Responses / Schema" ;;
                "Reference Object") search_pattern="Reference Object\|References" ;;
                "OAuth Flows") search_pattern="OAuth Flows" ;;
                "Security Requirement Object") search_pattern="Security Requirement\|Security Definitions" ;;
                "Links / Callbacks") search_pattern="Links / Callbacks\|Callbacks" ;;
                "Webhooks") search_pattern="Webhooks" ;;
            esac

            # Use grep to find the line with the feature.
            if grep -qi "$search_pattern.*✅" "$toolchain/COMPLIANCE.md" || grep -qi "$search_pattern.*[Ss]upported" "$toolchain/COMPLIANCE.md" || grep -qi "$search_pattern.*[Ii]mplemented" "$toolchain/COMPLIANCE.md"; then
                status="✅"
            # Special logic for cdd-go since it uses a bulleted list "Currently Supported" vs "To Be Implemented"
            elif [ "$toolchain" = "cdd-go" ]; then
                 if [ "$feature" = "Operation Object" ] || [ "$feature" = "Paths Object" ] || [ "$feature" = "Components Object" ]; then
                    status="✅"
                 fi
            # Submodules that claim 100% compliance broadly in the text
            elif grep -qi "100% compliance" "$toolchain/COMPLIANCE.md" || grep -qi "100% compliant" "$toolchain/COMPLIANCE.md"; then
                 status="✅"
            fi
        fi
        
        row="$row $status |"
    done
    
    echo "$row" >> "$OUTPUT_FILE"
done

cat << 'EOF' >> "$OUTPUT_FILE"

## Feature Definitions

*   **Info Object:** Parsing and emitting metadata about the API (title, version, description).
*   **Server Object:** Extracting server URLs and variable substitutions.
*   **Components Object:** Reusable schemas, responses, parameters, etc.
*   **Paths Object:** Routing definitions and endpoints.
*   **Path Item Object:** Operations available on a single path.
*   **Operation Object:** HTTP methods (GET, POST, etc.) and their specific details.
*   **Parameter Object:** Query, header, path, or cookie parameters.
*   **Request Body Object:** Request payloads.
*   **Responses Object:** Expected responses from an operation.
*   **Responses / Schema Object:** The data model of a response.
*   **Reference Object:** Resolving `$ref` pointers (internal and external).
*   **OAuth Flows:** Extracting OAuth2 security scheme definitions.
*   **Security Requirement Object:** Applying security schemes to operations.
*   **Links / Callbacks:** Advanced operation workflows.
*   **Webhooks:** Out-of-band callbacks.
EOF

echo "COMPLIANCE.md dashboard generated successfully."
